[package]
name = "jsonfmt"
version = "0.1.0"
edition = "2024"

[dependencies]
atty = "0.2.14"
clap = { version = "4.5.47", features = ["derive"] }
serde_json = "1.0"
serde = { version = "1.0.225", features = ["derive"] }  # 用于JSON解析和格式化
